import json
import urllib
import urllib.request
import json
import operator

def get_http_ping_result(rec_count,begin_time,end_time,area):
    url = 'http://kbxpn.51vv.com/api/console/proxy?path=_search&method=GET'
    params = """{
    "size": %d,
    "sort": [
        {
        "@timestamp": {
            "order": "desc",
            "unmapped_type": "boolean"
        }
        }
    ],
    "version": true,
    "aggs": {
        "2": {
        "date_histogram": {
            "field": "@timestamp",
            "fixed_interval": "30m",
            "time_zone": "Asia/Shanghai",
            "min_doc_count": 1
        }
        }
    },
    "fields": [
        {
        "field": "@timestamp",
        "format": "date_time"
        }
    ],
        "query": {
        "bool": {
        "must": [],
        "filter": [
            {
            "match_all": {}
            },
            {
            "range": {
                "@timestamp": {
                "gte": "%s",
                "lte": "%s",
                "format": "strict_date_optional_time"
                }
            }
            },
            {
            "match_phrase": {
                "evtKey": "app_list"
            }
            },
            {
            "match_phrase": {
                "geoip.country_name": "%s"
            }
            }
        ],
        "should": [],
        "must_not": []
        }
    },
    "script_fields": {},
    "stored_fields": [
        "@timestamp",
        "@version",
        "X-CLIENT",
        "X-CLIENT.keyword",
        "X-TIMEZONE",
        "X-TIMEZONE.keyword",
        "_id",
        "_index",
        "_score",
        "_source",
        "_type",
        "appInstallTime",
        "brand_model",
        "brand_model.keyword",
        "clickTimeServerSeconds",
        "client_ip",
        "client_ip.keyword",
        "cloud.instance.id",
        "cloud.instance.id.keyword",
        "cloud.provider",
        "cloud.provider.keyword",
        "cloud.region",
        "cloud.region.keyword",
        "ecs.version",
        "ecs.version.keyword",
        "evtKey",
        "evtKey.keyword",
        "fb_instance_id",
        "fb_instance_id.keyword",
        "geoip.city_name",
        "geoip.city_name.keyword",
        "geoip.continent_code",
        "geoip.continent_code.keyword",
        "geoip.country_code2",
        "geoip.country_code2.keyword",
        "geoip.country_code3",
        "geoip.country_code3.keyword",
        "geoip.country_name",
        "geoip.country_name.keyword",
        "geoip.dma_code",
        "geoip.ip",
        "geoip.latitude",
        "geoip.location",
        "geoip.longitude",
        "geoip.postal_code",
        "geoip.postal_code.keyword",
        "geoip.region_code",
        "geoip.region_code.keyword",
        "geoip.region_name",
        "geoip.region_name.keyword",
        "geoip.timezone",
        "geoip.timezone.keyword",
        "gmt",
        "gmt.keyword",
        "input.type",
        "input.type.keyword",
        "installBegin",
        "instantLaunched",
        "isForeground",
        "lag_seconds",
        "language",
        "language.keyword",
        "log.file.path",
        "log.file.path.keyword",
        "log.offset",
        "logtype",
        "logtype.keyword",
        "machine_os",
        "machine_os.keyword",
        "manufacturer",
        "manufacturer.keyword",
        "mid",
        "mid.keyword",
        "module",
        "module.keyword",
        "network",
        "network.keyword",
        "os_language",
        "os_language.keyword",
        "pageName",
        "pageName.keyword",
        "referrerClickTime",
        "referrerUrl",
        "referrerUrl.keyword",
        "report_time",
        "report_time.keyword",
        "romVersion",
        "romVersion.keyword",
        "serverlog_time",
        "serverlog_time.keyword",
        "tags",
        "tags.keyword",
        "target",
        "target.keyword",
        "timestamp",
        "userId",
        "user_agent",
        "user_agent.keyword",
        "value.X-REQID",
        "value.X-REQID.keyword",
        "value.action",
        "value.action.keyword",
        "value.app",
        "value.app.keyword",
        "value.code",
        "value.code.keyword",
        "value.error",
        "value.error.keyword",
        "value.errorKey",
        "value.errorKey.keyword",
        "value.errorType",
        "value.errorType.keyword",
        "value.errorValue.X-CLIENT",
        "value.errorValue.X-CLIENT.keyword",
        "value.errorValue.X-REQID",
        "value.errorValue.X-REQID.keyword",
        "value.errorValue.code",
        "value.errorValue.code.keyword",
        "value.errorValue.error",
        "value.errorValue.error.keyword",
        "value.errorValue.errorKey",
        "value.errorValue.errorKey.keyword",
        "value.errorValue.errorType",
        "value.errorValue.errorType.keyword",
        "value.errorValue.errorValue.X-CLIENT",
        "value.errorValue.errorValue.X-CLIENT.keyword",
        "value.errorValue.errorValue.X-REQID",
        "value.errorValue.errorValue.X-REQID.keyword",
        "value.errorValue.errorValue.code",
        "value.errorValue.errorValue.code.keyword",
        "value.errorValue.errorValue.error",
        "value.errorValue.errorValue.error.keyword",
        "value.errorValue.errorValue.errorKey",
        "value.errorValue.errorValue.errorKey.keyword",
        "value.errorValue.errorValue.errorType",
        "value.errorValue.errorValue.errorType.keyword",
        "value.errorValue.errorValue.errorValue.X-CLIENT",
        "value.errorValue.errorValue.errorValue.X-CLIENT.keyword",
        "value.errorValue.errorValue.errorValue.X-REQID",
        "value.errorValue.errorValue.errorValue.X-REQID.keyword",
        "value.errorValue.errorValue.errorValue.code",
        "value.errorValue.errorValue.errorValue.code.keyword",
        "value.errorValue.errorValue.errorValue.error",
        "value.errorValue.errorValue.errorValue.error.keyword",
        "value.errorValue.errorValue.errorValue.errorKey",
        "value.errorValue.errorValue.errorValue.errorKey.keyword",
        "value.errorValue.errorValue.errorValue.errorType",
        "value.errorValue.errorValue.errorValue.errorType.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.X-CLIENT",
        "value.errorValue.errorValue.errorValue.errorValue.X-CLIENT.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.X-REQID",
        "value.errorValue.errorValue.errorValue.errorValue.X-REQID.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.code",
        "value.errorValue.errorValue.errorValue.errorValue.code.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.error",
        "value.errorValue.errorValue.errorValue.errorValue.error.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorKey",
        "value.errorValue.errorValue.errorValue.errorValue.errorKey.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorType",
        "value.errorValue.errorValue.errorValue.errorValue.errorType.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.X-CLIENT",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.X-CLIENT.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.X-REQID",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.X-REQID.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.code",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.code.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.error",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.error.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorKey",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorKey.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorType",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorType.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.X-CLIENT",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.X-CLIENT.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.X-REQID",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.X-REQID.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.code",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.code.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.error",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.error.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.failMsg",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.failMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.flag",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.hasToken",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.ip",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.ip.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.isForeground",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.isForeground.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.isSuccess",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.language",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.language.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.mid",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.mid.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.msgLength",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.network",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.network.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.os_language",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.os_language.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.pageName",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.pageName.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.pingUrl",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.pingUrl.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.protocol",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.protocol.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.result",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.result.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.retMsg",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.retMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.server_address",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.server_address.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.server_port",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.session_id",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.session_id.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.step",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.step.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.time",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.timestamp",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.timestamp.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.toastMsg",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.toastMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.url",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.url.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.pingUrl",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.pingUrl.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.resp",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.serverIp",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.serverIp.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.serverPort",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.ttl",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.vpn_server_connected",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.vpn_server_connected.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.x-server-addr",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.errorValue.x-server-addr.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.failMsg",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.failMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.flag",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.hasToken",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.ip",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.ip.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.isForeground",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.isForeground.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.isSuccess",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.language",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.language.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.mid",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.mid.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.msgLength",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.network",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.network.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.os_language",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.os_language.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.pageName",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.pageName.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.pingUrl",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.pingUrl.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.protocol",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.protocol.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.result",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.result.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.retMsg",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.retMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.server_address",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.server_address.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.server_port",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.session_id",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.session_id.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.step",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.step.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.time",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.timestamp",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.timestamp.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.toastMsg",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.toastMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.url",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.url.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.pingUrl",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.pingUrl.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.resp",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.serverIp",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.serverIp.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.serverPort",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.value_obj.ttl",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.vpn_server_connected",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.vpn_server_connected.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.x-server-addr",
        "value.errorValue.errorValue.errorValue.errorValue.errorValue.x-server-addr.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.failMsg",
        "value.errorValue.errorValue.errorValue.errorValue.failMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.flag",
        "value.errorValue.errorValue.errorValue.errorValue.hasToken",
        "value.errorValue.errorValue.errorValue.errorValue.ip",
        "value.errorValue.errorValue.errorValue.errorValue.ip.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.isForeground",
        "value.errorValue.errorValue.errorValue.errorValue.isForeground.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.isSuccess",
        "value.errorValue.errorValue.errorValue.errorValue.language",
        "value.errorValue.errorValue.errorValue.errorValue.language.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.mid",
        "value.errorValue.errorValue.errorValue.errorValue.mid.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.msgLength",
        "value.errorValue.errorValue.errorValue.errorValue.network",
        "value.errorValue.errorValue.errorValue.errorValue.network.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.os_language",
        "value.errorValue.errorValue.errorValue.errorValue.os_language.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.pageName",
        "value.errorValue.errorValue.errorValue.errorValue.pageName.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.pingUrl",
        "value.errorValue.errorValue.errorValue.errorValue.pingUrl.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.protocol",
        "value.errorValue.errorValue.errorValue.errorValue.protocol.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.result",
        "value.errorValue.errorValue.errorValue.errorValue.result.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.retMsg",
        "value.errorValue.errorValue.errorValue.errorValue.retMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.server_address",
        "value.errorValue.errorValue.errorValue.errorValue.server_address.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.server_port",
        "value.errorValue.errorValue.errorValue.errorValue.session_id",
        "value.errorValue.errorValue.errorValue.errorValue.session_id.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.step",
        "value.errorValue.errorValue.errorValue.errorValue.step.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.time",
        "value.errorValue.errorValue.errorValue.errorValue.timestamp",
        "value.errorValue.errorValue.errorValue.errorValue.timestamp.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.toastMsg",
        "value.errorValue.errorValue.errorValue.errorValue.toastMsg.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.url",
        "value.errorValue.errorValue.errorValue.errorValue.url.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.value_obj.pingUrl",
        "value.errorValue.errorValue.errorValue.errorValue.value_obj.pingUrl.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.value_obj.resp",
        "value.errorValue.errorValue.errorValue.errorValue.value_obj.serverIp",
        "value.errorValue.errorValue.errorValue.errorValue.value_obj.serverIp.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.value_obj.serverPort",
        "value.errorValue.errorValue.errorValue.errorValue.value_obj.ttl",
        "value.errorValue.errorValue.errorValue.errorValue.vpn_server_connected",
        "value.errorValue.errorValue.errorValue.errorValue.vpn_server_connected.keyword",
        "value.errorValue.errorValue.errorValue.errorValue.x-server-addr",
        "value.errorValue.errorValue.errorValue.errorValue.x-server-addr.keyword",
        "value.errorValue.errorValue.errorValue.failMsg",
        "value.errorValue.errorValue.errorValue.failMsg.keyword",
        "value.errorValue.errorValue.errorValue.flag",
        "value.errorValue.errorValue.errorValue.hasToken",
        "value.errorValue.errorValue.errorValue.ip",
        "value.errorValue.errorValue.errorValue.ip.keyword",
        "value.errorValue.errorValue.errorValue.isForeground",
        "value.errorValue.errorValue.errorValue.isForeground.keyword",
        "value.errorValue.errorValue.errorValue.isSuccess",
        "value.errorValue.errorValue.errorValue.language",
        "value.errorValue.errorValue.errorValue.language.keyword",
        "value.errorValue.errorValue.errorValue.mid",
        "value.errorValue.errorValue.errorValue.mid.keyword",
        "value.errorValue.errorValue.errorValue.msgLength",
        "value.errorValue.errorValue.errorValue.network",
        "value.errorValue.errorValue.errorValue.network.keyword",
        "value.errorValue.errorValue.errorValue.os_language",
        "value.errorValue.errorValue.errorValue.os_language.keyword",
        "value.errorValue.errorValue.errorValue.pageName",
        "value.errorValue.errorValue.errorValue.pageName.keyword",
        "value.errorValue.errorValue.errorValue.pingUrl",
        "value.errorValue.errorValue.errorValue.pingUrl.keyword",
        "value.errorValue.errorValue.errorValue.protocol",
        "value.errorValue.errorValue.errorValue.protocol.keyword",
        "value.errorValue.errorValue.errorValue.result",
        "value.errorValue.errorValue.errorValue.result.keyword",
        "value.errorValue.errorValue.errorValue.retMsg",
        "value.errorValue.errorValue.errorValue.retMsg.keyword",
        "value.errorValue.errorValue.errorValue.server_address",
        "value.errorValue.errorValue.errorValue.server_address.keyword",
        "value.errorValue.errorValue.errorValue.server_port",
        "value.errorValue.errorValue.errorValue.session_id",
        "value.errorValue.errorValue.errorValue.session_id.keyword",
        "value.errorValue.errorValue.errorValue.step",
        "value.errorValue.errorValue.errorValue.step.keyword",
        "value.errorValue.errorValue.errorValue.time",
        "value.errorValue.errorValue.errorValue.timestamp",
        "value.errorValue.errorValue.errorValue.timestamp.keyword",
        "value.errorValue.errorValue.errorValue.toastMsg",
        "value.errorValue.errorValue.errorValue.toastMsg.keyword",
        "value.errorValue.errorValue.errorValue.url",
        "value.errorValue.errorValue.errorValue.url.keyword",
        "value.errorValue.errorValue.errorValue.value_obj.pingUrl",
        "value.errorValue.errorValue.errorValue.value_obj.pingUrl.keyword",
        "value.errorValue.errorValue.errorValue.value_obj.resp",
        "value.errorValue.errorValue.errorValue.value_obj.serverIp",
        "value.errorValue.errorValue.errorValue.value_obj.serverIp.keyword",
        "value.errorValue.errorValue.errorValue.value_obj.serverPort",
        "value.errorValue.errorValue.errorValue.value_obj.ttl",
        "value.errorValue.errorValue.errorValue.vpn_server_connected",
        "value.errorValue.errorValue.errorValue.vpn_server_connected.keyword",
        "value.errorValue.errorValue.errorValue.x-server-addr",
        "value.errorValue.errorValue.errorValue.x-server-addr.keyword",
        "value.errorValue.errorValue.failMsg",
        "value.errorValue.errorValue.failMsg.keyword",
        "value.errorValue.errorValue.flag",
        "value.errorValue.errorValue.hasToken",
        "value.errorValue.errorValue.ip",
        "value.errorValue.errorValue.ip.keyword",
        "value.errorValue.errorValue.isForeground",
        "value.errorValue.errorValue.isForeground.keyword",
        "value.errorValue.errorValue.isSuccess",
        "value.errorValue.errorValue.language",
        "value.errorValue.errorValue.language.keyword",
        "value.errorValue.errorValue.mid",
        "value.errorValue.errorValue.mid.keyword",
        "value.errorValue.errorValue.msgLength",
        "value.errorValue.errorValue.network",
        "value.errorValue.errorValue.network.keyword",
        "value.errorValue.errorValue.os_language",
        "value.errorValue.errorValue.os_language.keyword",
        "value.errorValue.errorValue.pageName",
        "value.errorValue.errorValue.pageName.keyword",
        "value.errorValue.errorValue.pingUrl",
        "value.errorValue.errorValue.pingUrl.keyword",
        "value.errorValue.errorValue.protocol",
        "value.errorValue.errorValue.protocol.keyword",
        "value.errorValue.errorValue.result",
        "value.errorValue.errorValue.result.keyword",
        "value.errorValue.errorValue.retMsg",
        "value.errorValue.errorValue.retMsg.keyword",
        "value.errorValue.errorValue.server_address",
        "value.errorValue.errorValue.server_address.keyword",
        "value.errorValue.errorValue.server_port",
        "value.errorValue.errorValue.session_id",
        "value.errorValue.errorValue.session_id.keyword",
        "value.errorValue.errorValue.step",
        "value.errorValue.errorValue.step.keyword",
        "value.errorValue.errorValue.time",
        "value.errorValue.errorValue.timestamp",
        "value.errorValue.errorValue.timestamp.keyword",
        "value.errorValue.errorValue.toastMsg",
        "value.errorValue.errorValue.toastMsg.keyword",
        "value.errorValue.errorValue.url",
        "value.errorValue.errorValue.url.keyword",
        "value.errorValue.errorValue.value_obj.pingUrl",
        "value.errorValue.errorValue.value_obj.pingUrl.keyword",
        "value.errorValue.errorValue.value_obj.resp",
        "value.errorValue.errorValue.value_obj.serverIp",
        "value.errorValue.errorValue.value_obj.serverIp.keyword",
        "value.errorValue.errorValue.value_obj.serverPort",
        "value.errorValue.errorValue.value_obj.ttl",
        "value.errorValue.errorValue.vpn_server_connected",
        "value.errorValue.errorValue.vpn_server_connected.keyword",
        "value.errorValue.errorValue.x-server-addr",
        "value.errorValue.errorValue.x-server-addr.keyword",
        "value.errorValue.failMsg",
        "value.errorValue.failMsg.keyword",
        "value.errorValue.flag",
        "value.errorValue.hasToken",
        "value.errorValue.ip",
        "value.errorValue.ip.keyword",
        "value.errorValue.isForeground",
        "value.errorValue.isForeground.keyword",
        "value.errorValue.isSuccess",
        "value.errorValue.language",
        "value.errorValue.language.keyword",
        "value.errorValue.mid",
        "value.errorValue.mid.keyword",
        "value.errorValue.msgLength",
        "value.errorValue.network",
        "value.errorValue.network.keyword",
        "value.errorValue.os_language",
        "value.errorValue.os_language.keyword",
        "value.errorValue.pageName",
        "value.errorValue.pageName.keyword",
        "value.errorValue.pingUrl",
        "value.errorValue.pingUrl.keyword",
        "value.errorValue.protocol",
        "value.errorValue.protocol.keyword",
        "value.errorValue.resp",
        "value.errorValue.result",
        "value.errorValue.result.keyword",
        "value.errorValue.retMsg",
        "value.errorValue.retMsg.keyword",
        "value.errorValue.serverIp",
        "value.errorValue.serverIp.keyword",
        "value.errorValue.serverPort",
        "value.errorValue.server_address",
        "value.errorValue.server_address.keyword",
        "value.errorValue.server_port",
        "value.errorValue.session_id",
        "value.errorValue.session_id.keyword",
        "value.errorValue.step",
        "value.errorValue.step.keyword",
        "value.errorValue.time",
        "value.errorValue.timestamp",
        "value.errorValue.timestamp.keyword",
        "value.errorValue.toastMsg",
        "value.errorValue.toastMsg.keyword",
        "value.errorValue.ttl",
        "value.errorValue.url",
        "value.errorValue.url.keyword",
        "value.errorValue.value_obj.pingUrl",
        "value.errorValue.value_obj.pingUrl.keyword",
        "value.errorValue.value_obj.resp",
        "value.errorValue.value_obj.serverIp",
        "value.errorValue.value_obj.serverIp.keyword",
        "value.errorValue.value_obj.serverPort",
        "value.errorValue.value_obj.ttl",
        "value.errorValue.vpn_server_address",
        "value.errorValue.vpn_server_address.keyword",
        "value.errorValue.vpn_server_connected",
        "value.errorValue.vpn_server_connected.keyword",
        "value.errorValue.vpn_server_port",
        "value.errorValue.vpn_server_port.keyword",
        "value.errorValue.x-server-addr",
        "value.errorValue.x-server-addr.keyword",
        "value.error_code",
        "value.error_code.keyword",
        "value.error_message",
        "value.error_message.keyword",
        "value.event",
        "value.event.keyword",
        "value.failMsg",
        "value.failMsg.keyword",
        "value.flag",
        "value.hasToken",
        "value.ip",
        "value.ip.keyword",
        "value.isNetAvailable",
        "value.isSuccess",
        "value.is_open",
        "value.key",
        "value.key.keyword",
        "value.lastPageName",
        "value.lastPageName.keyword",
        "value.message",
        "value.message.keyword",
        "value.msgLength",
        "value.name",
        "value.name.keyword",
        "value.netType",
        "value.netType.keyword",
        "value.page",
        "value.page.keyword",
        "value.page_event",
        "value.page_event.keyword",
        "value.pid",
        "value.pingUrl",
        "value.pingUrl.keyword",
        "value.protocol",
        "value.protocol.keyword",
        "value.result",
        "value.result.keyword",
        "value.retMsg",
        "value.retMsg.keyword",
        "value.server_address",
        "value.server_address.keyword",
        "value.server_port",
        "value.sessionId",
        "value.sessionId.keyword",
        "value.session_id",
        "value.session_id.keyword",
        "value.stayTime",
        "value.step",
        "value.step.keyword",
        "value.time",
        "value.toastMsg",
        "value.toastMsg.keyword",
        "value.trafficOutbounds",
        "value.trafficOutboundsDown",
        "value.trafficOutboundsTotal",
        "value.trafficOutboundsTotalDown",
        "value.trafficOutboundsTotalUp",
        "value.trafficOutboundsUp",
        "value.type",
        "value.type.keyword",
        "value.url",
        "value.url.keyword",
        "value.value",
        "value.value.keyword",
        "value.value_obj.pingUrl",
        "value.value_obj.pingUrl.keyword",
        "value.value_obj.resp",
        "value.value_obj.serverIp",
        "value.value_obj.serverIp.keyword",
        "value.value_obj.serverPort",
        "value.value_obj.ttl",
        "value.x-server-addr",
        "value.x-server-addr.keyword",
        "vpn_server_address",
        "vpn_server_address.keyword",
        "vpn_server_connected",
        "vpn_server_port",
        "vv_channel",
        "vv_channel.keyword",
        "vv_cver",
        "vv_cver.keyword",
        "vv_mid",
        "vv_mid.keyword",
        "vv_mname",
        "vv_mname.keyword",
        "vv_ochannel",
        "vv_ochannel.keyword",
        "vv_prod",
        "vv_prod.keyword",
        "vv_pver",
        "vv_pver.keyword"
    ],
    "runtime_mappings": {},
    "_source": {
        "excludes": []
    },
    "highlight": {
        "pre_tags": [
        "@kibana-highlighted-field@"
        ],
        "post_tags": [
        "@/kibana-highlighted-field@"
        ],
        "fields": {
        "*": {}
        },
        "fragment_size": 2147483647
    }
    }
    """
    params=params%(rec_count,begin_time,end_time,area)
    #params = json.dumps(params)
    headers = {'Accept-Charset': 'utf-8', 
    'Content-Type': 'application/json',
    'Origin':'http://kbxpn.51vv.com',
    'Referer':'http://kbxpn.51vv.com/app/dev_tools',
    'kbn-xsrf':'kibana',
    'Accept':'text/plain, */*; q=0.01'
    }
    #用bytes函数转换为字节
    params = bytes(params, 'utf8')
    #print(params)
    #proxy = {'http':'127.0.0.1:8888'}
    #proxy_handler = urllib.request.ProxyHandler(proxy)
    #opener = urllib.request.build_opener(proxy_handler)
    #urllib.request.install_opener(opener)
    #rsp = request.urlopen(url)
    #html = rsp.read().decode()
    #print(html)



    req = urllib.request.Request(url=url, data=params, headers=headers, method='POST')
    response = urllib.request.urlopen(req).read()
    return response 
#print(response.decode('utf-8'))

#写入json文件
#fo = open("e:\\http_ping_result.json", "wb")
#fo.write(response)
 
# 关闭打开的文件
#fo.close()

def parse_result(response):
    j = json.loads(response)
    #j = json.loads(open('e:\\http_ping_result.json','rb'))
    #print(j)
    arr = {}
    for rec in j['hits']['hits']:
        try:
            value_obj = rec['_source']
            value = rec['_source']['value']
            vv_mid = value_obj['vv_mid']
            apps = value['app']
            #print(vv_mid,apps)
            arr[vv_mid] = apps
        except Exception as e:
            print(e)
    arr_pkg_name = {}
    for k in arr.keys():
        v = json.loads(arr[k])
        for v1 in v:
            if not v1['packageName'] in arr_pkg_name:
                arr_pkg_name[v1['packageName']] = 0
            arr_pkg_name[v1['packageName']] += 1
            #print('%s\t%s\t%s'%(k,v1['appName'],v1['packageName']))
            #print('%s\t%s\t%s'%(k,v1['appName'],v1['packageName']))
    sorted_x = sorted(arr_pkg_name.items(), key=operator.itemgetter(1), reverse=True)
    for item in sorted_x:
        print(item[0],item[1])
    #for k in sorted_x:
    #    print(k,sorted_x[k])

def main():
    resp = get_http_ping_result(rec_count=10000,begin_time='2022-11-18',end_time='2022-11-28',area='Iran')
    parse_result(resp)
    #print(resp)
    #"gte": "2022-11-21T01:53:46.251Z",
    #"lte": "2022-11-25T01:53:46.251Z",


if __name__ == '__main__':
    main()